sudo: required
language: ruby
services:
- docker
before_install:
  #- sudo apt-get -qq update
  #  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
script:
  - docker build -f nginx/Dockerfile -t apsl/nginx-proxy-htpasswd nginx/
  - docker tag apsl/nginx-proxy-htpasswd apsl/nginx-proxy-htpasswd:$VERSION
  - docker tag apsl/nginx-proxy-htpasswd apsl/nginx-proxy-htpasswd:latest
notifications:
  email:
  - gshark@gmail.com
env:
  global:
  - VERSION=1.0
  - secure: ud5dpkNd0fLOLNcT9D9wHNpra/37eKuj0MUq4Gobl87tZEuBcGkU6Zhglwi6j9Uspii9yuEflEDfrizG4hFvnzo0baLh9P4zugMawK0/S8fEOhp1iy4MJOaGXVttQLfus0NI8EdgeDoXt3luG3qVaT/bpSEGoi6xmkwSWu1czxljzjJehrrspCC59+iIgXBIcf9jj3D3P3IQc0bo7FlQHjLWILX5ZNN4mU0JAHM3AT2gHJMXCrDXyz/il0+L+mX89Qxrw6HLFTe7zqUX4EdJcNTcG+Amsw0MNX0BERT25MYhNbaRBtoxNu0EQnRaxRS2++NDMgizDFsSXoMdrXeIN5WFIvx4/5V1+k97dbgToyiUdDf7svLRmfUzBjOFQVKAxyZE+7f8rhS4RKgk2if1/LnC9x/KqmKDenbyxgLoDpkea1gX5GhOiEIN0LN4Vcs6uY9VC+gMiFR6d/kbTDOW95UM5y3UIodeWI/TvpRkzOldjk14aNNn1MXIafq0b2ZHzHsc3Mn66ozbNBWXqIkq8CjHR/ubko5RHsdpKZYilUKXf1rWSzZM36lYDgwG+JAXCk2QHQcGBkbxQSzbniidGvZLXdwc5Ahz5eQb2G2yB9qpQFoAJAnSwOcKA56E8dJHSC98ai1s8snLwZEsoUETfCHhLTN0cjavlSeVK1L5R+g=
  - secure: gCQF7fvMtcAculLwZn/kieqmGlPyHQ9KlmftyEiAJJfESGIQhg2du8kbOrwVPHnuHqIrqSBv5bdzpdqf10H+N0DSHUU0cjCDql5cfkOYoBFpp2eNnRxRbrvNgx3eTsklIfYIVvNSWTKSaDT6pEuMLxr5otXqxrN3W/CM7X40JonUiud/IgRYmhdXVBznuk51FSIJ8xnCyBNBX2EvgSJK+QTCPg5t2J66iGKC2KgK5ol3hjpQqzbiJeyb0WX1wYaRQGyvSekKXd8M8bDgGRMj4ZXVWL/4LmTmn8c/dxEGZdyqUMFh20E4VB+o5PEUk1SZ3TwM3Y+T+ogtMK6TgbesVC3poerSXbnF2f5LINsedRXJDW5zULbXnkgQZ+8ed/FaNJZWZ/YQC4IqO7mj2IHzU/V3iuMQzqVrxAI6SlEcJUeKScSdFkwM7IiXHEFunErws64C6kTemus3g0YMxHg4ewYYhktClB3sHyl6fTel8x9o7L/RYAN5QeUSW6ZwSvOM1WBrdhSEAnYzYJk/gYkv6AE/M5lnN/388kG6yGwjHOA+1Bywhf2ByG7OxuB3ewZGvaZbEJWce6ZO0spnj7NRH6h7uzMIOxNRE511HvcfE8QFswNzxj/mShF6S0fIe+cBZ6+thdq3mNTfP2bP4G7FYcgBgJ0Ao0SqynWNpxZ3u48= 
  - secure: Y1CDlgLSdl4ZkqslmxoYX2PBoFb9GsvwNtfo8f6HhJprwMZyFhgwrLRSh2kUSO9EAAIaJTHcfEYnlTHGKibjbvsdj+WyHrwlB0TWM+lSjbFNBXE2C6DvGs/iYq+OjvI8akPO+OvxVfmkATZ69vs7dgwSFTfp0dcttNc3hCubv9q2x0gcLPzRLh56n9YohiyKOGqwduUHA9XpEU/07yHGPw9oDZjWrbewUqFS+q1DNTSR5/BjcHeOMzjXDb6LYr8U3OfR31kdcFrElzgF5Vj5BNoYzsrnkgUKBiTOj9ZKNYkDHncRa6zIpQ4pSFxNhGHlRNTBQZRG8nLlm5EqOl5ql9pkcaZbhoMYVA6tFRaRXlzT1u79OQ5o3tueNgrHBf8VcwrwTBakJerVv4SRLuDxQDbQjHffiDQnuF2mmTx4kGN0xCimq7QciQaMPdYNYrkzVCXpoYgihdOccH0FvjmDGIGsTE9K3vX8tq/iem8ivATFi1w2vvJXuCZ0kK4lsiOissHKr9nVXyXK2sdM+2rbWrAo/Fre9epeaEZzcW/KfJy0dsVZ0vmYnBEb7iIp8/21LtMu80a8UAnYJkF4Zqr4vuw8zE19iEa73at6cc0rRfOOLW7uB6rt09IFHucwnAyoJ23FsfOlxY8iSBCxOhhpgSmDYq3Pb2z1p+QOHedQ2iw= 
  #- DOCKER_VERSION=1.11.1-0~trusty
  - DOCKER_COMPOSE_VERSION=1.8.0
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- docker push apsl/nginx-proxy-htpasswd:$VERSION
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker push apsl/nginx-proxy-htpasswd:latest ; fi;
- docker images -a
